const translations = {
    en: {
        subHeading: "Earth's orbit around the sun and Earth's rotation",
        firstHead: "The Earth's orbit <br> around the sun",
        firstBtn: "Start",
        foot: "what does the Earth's orbit around the sun look like?",
        secondHead:"Seasons",
        secondBtn:"Start",
        secondFoot:"What induces the seasons? How high is the sun over the year in different latitudes? And how would the situation change when the Earth's axis had a different slope?",
        thirdHead:"SolarTime",
        thirdBtn:"Start",
        thirdFoot:"What is the Solar Time and how long is a daytime at different places on the Earth?",
        fourthHead:"TimeZones",
        fourthBtn:"Start",
        fourthFoot:"What time is currently in different cities on the Earth? View an interactive map!(c) timeanddate.com",        
        secondSubHeading:"The MOON,the Eclipse and Tides",
        fifthHead:"Moon phases",
        fifthBtn:"Start",
        fifthFoot:"How do the moon phases that we can see from the Earth originate?",
        sixthHead:"Solar and Lunar eclipses",
        sixthBtn:"Start",
        sixthFoot:"Explore the mechanism of the Solar and Lunar eclipse! Why does the eclipse not occur every month?",
        seventhHead:"Future eclipse",
        seventhBtn:"Start",
        seventhFoot:"When will the solar or lunar eclipse occur in the future, and where will it be observable? (c) timeanddate.com",
        eighthHead:"Tidal phenomena",
        eighthBtn:"Start",
        eighthFoot:"What causes the tides? How do the tides change during the month?",
        thirdSubHeading:"Solar System",
        ninthHead:"Solar System",
        ninthBtn:"Start",
        ninthFoot:"Take an interactive walk through the Solar system.(c) Martin Vézina",
        tenthHead:"Distances and Dimensions",
        tenthBtn:"Start",
        tenthFoot:"Can you imagine what distances between the planets are and what dimensions the planets have? Experience a map application that will present these enormous distances and dimensions in a familiar environment.",
        footerHead:"About this site",
        footerHead:"Contact",
        footerHead:"Privacy Policy",
        footerHead:"Terms of Use",
        footerHead:"Feedback",
        footerHead:"Advertise with us",
        footerHead:"Site Map",
        footerHead:"press",
        footerHead:"imprint",
        footerHead:"Time and Date AS 2006-2020",
    },
    es: {
        subHeading: "La órbita de la Tierra alrededor del sol y la rotación de la Tierra",
        firtsHead: "La órbita de la Tierra <br> alrededor del sol",
        firstBtn: "Comenzar",
        foot: "¿Cómo es la órbita de la Tierra alrededor del sol?",
        secondHead: "Estaciones",
        secondBtn: "Comenzar",
        secondFoot: "¿Qué induce las estaciones? ¿Qué altura tiene el sol durante el año en diferentes latitudes? ¿Y cómo cambiaría la situación si el eje de la Tierra tuviera una inclinación diferente?",
        thirdHead: "Hora Solar",
        thirdBtn: "Comenzar",
        thirdFoot: "¿Qué es la Hora Solar y cuánto dura un día en diferentes lugares de la Tierra?",
        fourthHead: "Zonas horarias",
        fourthBtn: "Comenzar",
        fourthFoot: "¿Qué hora es actualmente en diferentes ciudades de la Tierra? ¡Vea un mapa interactivo! (c) timeanddate.com",
        secondSubHeading: "La LUNA, el Eclipse y las Mareas",
        fifthHead: "Fases de la Luna",
        fifthBtn: "Comenzar",
        fifthFoot: "¿Cómo se originan las fases de la luna que podemos ver desde la Tierra?",
        sixthHead: "Eclipses Solares y Lunares",
        sixthBtn: "Comenzar",
        sixthFoot: "¡Explora el mecanismo del eclipse solar y lunar! ¿Por qué el eclipse no ocurre cada mes?",
        seventhHead: "Eclipse futuro",
        seventhBtn: "Comenzar",
        seventhFoot: "¿Cuándo ocurrirá el eclipse solar o lunar en el futuro y dónde será observable? (c) timeanddate.com",
        eighthHead: "Fenómenos de marea",
        eighthBtn: "Comenzar",
        eighthFoot: "¿Qué causa las mareas? ¿Cómo cambian las mareas durante el mes?",
        thirdSubHeading: "Sistema Solar",
        ninthHead: "Sistema Solar",
        ninthBtn: "Comenzar",
        ninthFoot: "Realice un recorrido interactivo por el Sistema Solar. (c) Martin Vézina",
        tenthHead: "Distancias y dimensiones",
        tenthBtn: "Comenzar",
        tenthFoot: "¿Puedes imaginar qué distancias hay entre los planetas y qué dimensiones tienen los planetas? Experimente una aplicación de mapas que presentará estas enormes distancias y dimensiones en un entorno familiar.",
        footerHead: "Sobre este sitio",
        footerHead: "Contacto",
        footerHead: "Política de privacidad",
        footerHead: "Términos de uso",
        footerHead: "Comentarios",
        footerHead: "Anunciar con nosotros",
        footerHead: "Mapa del sitio",
        footerHead: "prensa",
        footerHead: "impresión",
        footerHead: "Hora y fecha AS 2006-2020",
    },
    fr: {
        subHeading: "L'orbite de la Terre autour du soleil et la rotation de la Terre",        
        firstHead: "L'orbite de la Terre <br> autour du soleil",
        firstBtn: "Commencer",
        foot: "À quoi ressemble l'orbite de la Terre autour du soleil?",
        secondHead: "Saisons",
        secondBtn: "Commencer",
        secondFoot: "Qu'est-ce qui induit les saisons? Quelle est la hauteur du soleil au cours de l'année à différentes latitudes? Et comment la situation changerait-elle si l'axe de la Terre avait une pente différente?",
        thirdHead: "Heure solaire",
        thirdBtn: "Commencer",
        thirdFoot: "Qu'est-ce que l'heure solaire et combien de temps dure une journée à différents endroits sur la Terre?",
        fourthHead: "Fuseaux horaires",
        fourthBtn: "Commencer",
        fourthFoot: "Quelle heure est-il actuellement dans différentes villes du monde? Voir une carte interactive! (c) timeanddate.com",
        secondSubHeading: "La LUNE, l'éclipse et les marées",
        fifthHead: "Phases de la lune",
        fifthBtn: "Commencer",
        fifthFoot: "Comment les phases de la lune que nous pouvons voir depuis la Terre se forment-elles?",
        sixthHead: "Éclipses solaires et lunaires",
        sixthBtn: "Commencer",
        sixthFoot: "Explorez le mécanisme de l'éclipse solaire et lunaire! Pourquoi l'éclipse ne se produit-elle pas chaque mois?",
        seventhHead: "Éclipse future",
        seventhBtn: "Commencer",
        seventhFoot: "Quand aura lieu l'éclipse solaire ou lunaire à l'avenir et où sera-t-elle observable? (c) timeanddate.com",
        eighthHead: "Phénomènes de marée",
        eighthBtn: "Commencer",
        eighthFoot: "Qu'est-ce qui cause les marées? Comment les marées changent-elles au cours du mois?",
        thirdSubHeading: "Système solaire",
        ninthHead: "Système solaire",
        ninthBtn: "Commencer",
        ninthFoot: "Faites une promenade interactive dans le système solaire. (c) Martin Vézina",
        tenthHead: "Distances et dimensions",
        tenthBtn: "Commencer",
        tenthFoot: "Pouvez-vous imaginer quelles sont les distances entre les planètes et quelles sont les dimensions des planètes? Découvrez une application cartographique qui présentera ces énormes distances et dimensions dans un environnement familier.",
        footerHead: "À propos de ce site",
        footerHead: "Contact",
        footerHead: "Politique de confidentialité",
        footerHead: "Conditions d'utilisation",
        footerHead: "Retour d'information",
        footerHead: "Annoncez avec nous",
        footerHead: "Plan du site",
        footerHead: "presse",
        footerHead: "impression",
        footerHead: "Heure et date AS 2006-2020",
    },
    de: {
        subHeading: "Die Umlaufbahn der Erde um die Sonne und die Rotation der Erde",
        firstHead: "Die Umlaufbahn der Erde <br> um die Sonne",
        firstBtn: "Start",
        foot: "Wie sieht die Umlaufbahn der Erde um die Sonne aus?",
        secondHead: "Jahreszeiten",
        secondBtn: "Start",
        secondFoot: "Was löst die Jahreszeiten aus? Wie hoch steht die Sonne im Laufe des Jahres in verschiedenen Breiten? Und wie würde sich die Situation ändern, wenn die Erdachse eine andere Neigung hätte?",
        thirdHead: "Sonnenuhr",
        thirdBtn: "Start",
        thirdFoot: "Was ist die Sonnenuhr und wie lange dauert ein Tag an verschiedenen Orten auf der Erde?",
        fourthHead: "Zeitzonen",
        fourthBtn: "Start",
        fourthFoot: "Wie spät ist es derzeit in verschiedenen Städten auf der Erde? Sehen Sie eine interaktive Karte! (c) timeanddate.com",
        secondSubHeading: "Der MOND, die Sonnen- und Mondfinsternisse und Gezeiten",
        fifthHead: "Mondphasen",
        fifthBtn: "Start",
        fifthFoot: "Wie entstehen die Mondphasen, die wir von der Erde aus sehen können?",
        sixthHead: "Sonnen- und Mondfinsternisse",
        sixthBtn: "Start",
        sixthFoot: "Erkunden Sie den Mechanismus der Sonnen- und Mondfinsternis! Warum tritt die Finsternis nicht jeden Monat auf?",
        seventhHead: "Zukünftige Finsternisse",
        seventhBtn: "Start",
        seventhFoot: "Wann wird die Sonnen- oder Mondfinsternis in der Zukunft stattfinden und wo wird sie beobachtbar sein? (c) timeanddate.com",
        eighthHead: "Gezeitenphänomene",
        eighthBtn: "Start",
        eighthFoot: "Was verursacht die Gezeiten? Wie verändern sich die Gezeiten im Laufe des Monats?",
        thirdSubHeading: "Sonnensystem",
        ninthHead: "Sonnensystem",
        ninthBtn: "Start",
        ninthFoot: "Machen Sie einen interaktiven Spaziergang durch das Sonnensystem. (c) Martin Vézina",
        tenthHead: "Entfernungen und Dimensionen",
        tenthBtn: "Start",
        tenthFoot: "Können Sie sich vorstellen, welche Abstände zwischen den Planeten liegen und welche Dimensionen die Planeten haben? Erleben Sie eine Kartenanwendung, die diese enormen Entfernungen und Dimensionen in einer vertrauten Umgebung präsentiert.",
        footerHead: "Über diese Seite",
        footerHead: "Kontakt",
        footerHead: "Datenschutz-Bestimmungen",
        footerHead: "Nutzungsbedingungen",
        footerHead: "Feedback",
        footerHead: "Werben Sie bei uns",
        footerHead: "Seitenverzeichnis",
        footerHead: "Presse",
        footerHead: "Impressum",
        footerHead: "Zeit und Datum AS 2006-2020",
    },
    it: {
        subHeading: "L'orbita della Terra intorno al sole e la rotazione della Terra",
        firstHead: "L'orbita della Terra <br> intorno al sole",
        firstBtn: "Inizio",
        foot: "Come appare l'orbita della Terra intorno al sole?",
        secondHead: "Stagioni",
        secondBtn: "Inizio",
        secondFoot: "Cosa induce le stagioni? Quanto è alto il sole durante l'anno a diverse latitudini? E come cambierebbe la situazione se l'asse della Terra avesse una pendenza diversa?",
        thirdHead: "Ora solare",
        thirdBtn: "Inizio",
        thirdFoot: "Cos'è l'Ora solare e quanto dura un giorno in diversi luoghi sulla Terra?",
        fourthHead: "Fusi orari",
        fourthBtn: "Inizio",
        fourthFoot: "Che ora è attualmente in diverse città del mondo? Guarda una mappa interattiva! (c) timeanddate.com",
        secondSubHeading: "La LUNA, l'eclissi e le maree",
        fifthHead: "Fasi lunari",
        fifthBtn: "Inizio",
        fifthFoot: "Come si originano le fasi lunari che possiamo vedere dalla Terra?",
        sixthHead: "Eclissi solari e lunari",
        sixthBtn: "Inizio",
        sixthFoot: "Esplora il meccanismo dell'eclissi solare e lunare! Perché l'eclissi non si verifica ogni mese?",
        seventhHead: "Eclissi future",
        seventhBtn: "Inizio",
        seventhFoot: "Quando si verificherà l'eclissi solare o lunare in futuro e dove sarà osservabile? (c) timeanddate.com",
        eighthHead: "Fenomeni di marea",
        eighthBtn: "Inizio",
        eighthFoot: "Cosa causa le maree? Come cambiano le maree durante il mese?",
        thirdSubHeading: "Sistema solare",
        ninthHead: "Sistema solare",
        ninthBtn: "Inizio",
        ninthFoot: "Fai una passeggiata interattiva attraverso il sistema solare. (c) Martin Vézina",
        tenthHead: "Distanze e dimensioni",
        tenthBtn: "Inizio",
        tenthFoot: "Riesci a immaginare quali siano le distanze tra i pianeti e quali dimensioni abbiano i pianeti? Vivi un'applicazione di mappe che presenterà queste enormi distanze e dimensioni in un ambiente familiare.",
        footerHead: "Informazioni su questo sito",
        footerHead: "Contatto",
        footerHead: "Normativa sulla privacy",
        footerHead: "Termini di utilizzo",
        footerHead: "Feedback",
        footerHead: "Pubblicità con noi",
        footerHead: "Mappa del sito",
        footerHead: "stampa",
        footerHead: "impronta",
        footerHead: "Ora e data AS 2006-2020",
    },
    pt: {
        subHeading: "A órbita da Terra ao redor do sol e a rotação da Terra",
        firstHead: "A órbita da Terra <br> ao redor do sol",
        firstBtn: "Começar",
        foot: "Como é a órbita da Terra ao redor do sol?",
        secondHead: "Estações",
        secondBtn: "Começar",
        secondFoot: "O que induz as estações? Qual é a altura do sol ao longo do ano em diferentes latitudes? E como a situação mudaria se o eixo da Terra tivesse uma inclinação diferente?",
        thirdHead: "Hora Solar",
        thirdBtn: "Começar",
        thirdFoot: "O que é a Hora Solar e quanto tempo dura um dia em diferentes lugares da Terra?",
        fourthHead: "Fusos horários",
        fourthBtn: "Começar",
        fourthFoot: "Que horas são atualmente em diferentes cidades do mundo? Veja um mapa interativo! (c) timeanddate.com",
        secondSubHeading: "A LUA, o Eclipse e as Marés",
        fifthHead: "Fases da Lua",
        fifthBtn: "Começar",
        fifthFoot: "Como se originam as fases da lua que podemos ver da Terra?",
        sixthHead: "Eclipses Solares e Lunares",
        sixthBtn: "Começar",
        sixthFoot: "Explore o mecanismo do eclipse solar e lunar! Por que o eclipse não ocorre todos os meses?",
        seventhHead: "Eclipse futuro",
        seventhBtn: "Começar",
        seventhFoot: "Quando ocorrerá o eclipse solar ou lunar no futuro e onde será observável? (c) timeanddate.com",
        eighthHead: "Fenômenos de maré",
        eighthBtn: "Começar",
        eighthFoot: "O que causa as marés? Como as marés mudam durante o mês?",
        thirdSubHeading: "Sistema Solar",
        ninthHead: "Sistema Solar",
        ninthBtn: "Começar",
        ninthFoot: "Faça uma caminhada interativa pelo Sistema Solar. (c) Martin Vézina",
        tenthHead: "Distâncias e Dimensões",
        tenthBtn: "Começar",
        tenthFoot: "Consegue imaginar quais são as distâncias entre os planetas e que dimensões têm os planetas? Experimente um aplicativo de mapas que apresentará essas enormes distâncias e dimensões em um ambiente familiar.",
        footerHead: "Sobre este site",
        footerHead: "Contato",
        footerHead: "Política de Privacidade",
        footerHead: "Termos de Uso",
        footerHead: "Comentários",
        footerHead: "Anuncie conosco",
        footerHead: "Mapa do site",
        footerHead: "impressão",
        footerHead: "impressão",
        footerHead: "Hora e Data AS 2006-2020",
    },
    ru: {
        subHeading: "Орбита Земли вокруг солнца и вращение Земли",
        firstHead: "Орбита Земли <br> вокруг солнца",
        firstBtn: "Начать",
        foot: "Как выглядит орбита Земли вокруг солнца?",
        secondHead: "Сезоны",
        secondBtn: "Начать",
        secondFoot: "Что вызывает сезоны? Какова высота солнца в течение года в разных широтах? И как бы изменилась ситуация, если бы ось Земли имела другой наклон?",
        thirdHead: "Солнечное время",
        thirdBtn: "Начать",
        thirdFoot: "Что такое Солнечное время и как долго длится день в разных местах на Земле?",
        fourthHead: "Часовые пояса",
        fourthBtn: "Начать",
        fourthFoot: "Который час в настоящее время в разных городах мира? Посмотрите интерактивную карту! (c) timeanddate.com",
        secondSubHeading: "ЛУНА, затмения и приливы",
        fifthHead: "Фазы Луны",
        fifthBtn: "Начать",
        fifthFoot: "Как возникают фазы Луны, которые мы видим с Земли?",
        sixthHead: "Солнечные и лунные затмения",
        sixthBtn: "Начать",
        sixthFoot: "Исследуйте механизм солнечного и лунного затмения! Почему затмение не происходит каждый месяц?",
        seventhHead: "Будущие затмения",
        seventhBtn: "Начать",
        seventhFoot: "Когда произойдет солнечное или лунное затмение в будущем и где оно будет наблюдаться? (c) timeanddate.com",
        eighthHead: "Приливные явления",
        eighthBtn: "Начать",
        eighthFoot: "Что вызывает приливы? Как меняются приливы в течение месяца?",
        thirdSubHeading: "Солнечная система",
        ninthHead: "Солнечная система",
        ninthBtn: "Начать",
        ninthFoot: "Пройдите интерактивную прогулку по Солнечной системе. (c) Martin Vézina",
        tenthHead: "Расстояния и размеры",
        tenthBtn: "Начать",
        tenthFoot: "Можете ли вы представить, какие расстояния между планетами и какие размеры у планет? Опыт приложения карты, которое представит эти огромные расстояния и размеры в знакомой среде.",
        footerHead: "Об этом сайте",
        footerHead: "Контакт",
        footerHead: "Политика конфиденциальности",
        footerHead: "Условия использования",
        footerHead: "Обратная связь",
        footerHead: "Реклама с нами",
        footerHead: "Карта сайта",
        footerHead: "печать",
        footerHead: "отпечаток",
        footerHead: "Время и дата AS 2006-2020",
    },
    zh: {
        subHeading: "地球绕太阳的轨道和地球的自转",
        firstHead: "地球绕太阳的轨道",
        firstBtn: "开始",
        foot: "地球绕太阳的轨道是什么样子的？",
        secondHead: "季节",
        secondBtn: "开始",
        secondFoot: "是什么导致了季节？在不同纬度的一年中太阳有多高？如果地球的轴有不同的倾斜度，情况会如何改变？",
        thirdHead: "太阳时间",
        thirdBtn: "开始",
        thirdFoot: "什么是太阳时间，不同地方的白天有多长？",
        fourthHead: "时区",
        fourthBtn: "开始",
        fourthFoot: "不同城市现在是几点？查看一个互动地图！(c) timeanddate.com",
        secondSubHeading: "月亮、日食和潮汐",
        fifthHead: "月相",
        fifthBtn: "开始",
        fifthFoot: "我们从地球上看到的月相是如何产生的？",
        sixthHead: "日食和月食",
        sixthBtn: "开始",
        sixthFoot: "探索日食和月食的机制！为什么日食不是每个月都发生？",
        seventhHead: "未来日食",
        seventhBtn: "开始",
        seventhFoot: "未来将发生日食或月食，将在哪里可见？(c) timeanddate.com",
        eighthHead: "潮汐现象",
        eighthBtn: "开始",
        eighthFoot: "是什么导致了潮汐？潮汐在一个月内如何变化？",
        thirdSubHeading: "太阳系",
        ninthHead: "太阳系",
        ninthBtn: "开始",
        ninthFoot: "通过太阳系进行互动漫步。(c) Martin Vézina",
        tenthHead: "距离和尺寸",
        tenthBtn: "开始",
        tenthFoot: "你能想象行星之间的距离是多少，行星有什么尺寸吗？体验一个地图应用程序，它将在熟悉的环境中展示这些巨大的距离和尺寸。",
        footerHead: "关于本站",
        footerHead: "联系",
        footerHead: "隐私政策",
        footerHead: "使用条款",
        footerHead: "反馈",
        footerHead: "与我们合作",
        footerHead: "网站地图",
        footerHead: "印刷",
        footerHead: "印记",
    },
    ja: {
        subHeading: "地球の太陽の周りの軌道と地球の自転",
        firstHead: "地球の軌道 <br> 太陽の周り",
        firstBtn: "開始",
        foot: "地球の太陽の周りの軌道はどのように見えますか？", 
        secondHead: "季節",
        secondBtn: "開始",
        secondFoot: "季節を引き起こすのは何ですか？異なる緯度での太陽の高さはどのように変化しますか？地球の軸が異なる傾斜を持っていた場合、状況はどのように変わるでしょうか？",
        thirdHead: "太陽時",
        thirdBtn: "開始",
        thirdFoot: "太陽時とは何ですか？地球上のさまざまな場所での昼間の長さはどのくらいですか？",
        fourthHead: "タイムゾーン",
        fourthBtn: "開始",
        fourthFoot: "現在、地球上のさまざまな都市で何時ですか？インタラクティブな地図を見る！(c) timeanddate.com",
        secondSubHeading: "月、日食、潮汐",
        fifthHead: "月相",
        fifthBtn: "開始",
        fifthFoot: "地球から見える月相はどのようにして生じるのでしょうか？",
        sixthHead: "日食と月食",
        sixthBtn: "開始",
        sixthFoot: "日食と月食のメカニズムを探索してください！なぜ月食は毎月起こらないのでしょうか？",
        seventhHead: "将来の日食",
        seventhBtn: "開始",
        seventhFoot: "将来、いつ、どこで日食または月食が起こるのでしょうか？(c) timeanddate.com",
        eighthHead: "潮汐現象",
        eighthBtn: "開始",
        eighthFoot: "潮汐は何を引き起こすのでしょうか？月の間に潮汐はどのように変化するのでしょうか？",
        thirdSubHeading: "太陽系",
        ninthHead: "太陽系",
        ninthBtn: "開始",
        ninthFoot: "太陽系をインタラクティブに歩いてみましょう。(c) Martin Vézina",
        tenthHead: "距離と寸法",
        tenthBtn: "開始",
        tenthFoot: "惑星間の距離や惑星の寸法を想像できますか？これらの巨大な距離と寸法をなじみのある環境で提示するマップアプリケーションを体験してください。",
        footerHead: "このサイトについて",
        footerHead: "お問い合わせ",
        footerHead: "プライバシーポリシー",
        footerHead: "利用規約",
        footerHead: "フィードバック",
        footerHead: "広告掲載",
        footerHead: "サイトマップ",
        footerHead: "印刷",
        footerHead: "印刷",
        footerHead: "Time and Date AS 2006-2020",
    },      
    
};

document.getElementById('language-dropdown').addEventListener('change', function() {
    const selectedLanguage = this.value;
    document.querySelector('.sub-heading').textContent = translations[selectedLanguage].subHeading;
    document.querySelector('.first-head').innerHTML = translations[selectedLanguage].firstHead;
    document.querySelector('.first-btn').textContent = translations[selectedLanguage].firstBtn;
    document.querySelector('.foot').textContent = translations[selectedLanguage].foot;
    document.querySelector('.second-head').textContent = translations[selectedLanguage].secondHead; 
    document.querySelector('.second-btn').textContent = translations[selectedLanguage].secondBtn;
    document.querySelector('.second-foot').textContent = translations[selectedLanguage].secondFoot;
    document.querySelector('.third-head').textContent = translations[selectedLanguage].thirdHead;
    document.querySelector('.third-btn').textContent = translations[selectedLanguage].thirdBtn;
    document.querySelector('.third-foot').textContent = translations[selectedLanguage].thirdFoot;
    document.querySelector('.fourth-head').textContent = translations[selectedLanguage].fourthHead;
    document.querySelector('.fourth-btn').textContent = translations[selectedLanguage].fourthBtn;
    document.querySelector('.fourth-foot').textContent = translations[selectedLanguage].fourthFoot;
    document.querySelector('.second-sub-heading').textContent = translations[selectedLanguage].secondSubHeading;
    document.querySelector('.fifth-head').textContent = translations[selectedLanguage].fifthHead;
    document.querySelector('.fifth-btn').textContent = translations[selectedLanguage].fifthBtn;
    document.querySelector('.fifth-foot').textContent = translations[selectedLanguage].fifthFoot;
    document.querySelector('.sixth-head').textContent = translations[selectedLanguage].sixthHead;
    document.querySelector('.sixth-btn').textContent = translations[selectedLanguage].sixthBtn;
    document.querySelector('.sixth-foot').textContent = translations[selectedLanguage].sixthFoot;
    document.querySelector('.seventh-head').textContent = translations[selectedLanguage].seventhHead;
    document.querySelector('.seventh-btn').textContent = translations[selectedLanguage].seventhBtn;
    document.querySelector('.seventh-foot').textContent = translations[selectedLanguage].seventhFoot;
    document.querySelector('.eighth-head').textContent = translations[selectedLanguage].eighthHead;
    document.querySelector('.eighth-btn').textContent = translations[selectedLanguage].eighthBtn;
    document.querySelector('.eighth-foot').textContent = translations[selectedLanguage].eighthFoot;
    document.querySelector('.third-sub-heading').textContent = translations[selectedLanguage].thirdSubHeading;
    document.querySelector('.ninth-head').textContent = translations[selectedLanguage].ninthHead;
    document.querySelector('.ninth-btn').textContent = translations[selectedLanguage].ninthBtn;
    document.querySelector('.ninth-foot').textContent = translations[selectedLanguage].ninthFoot;
    document.querySelector('.tenth-head').textContent = translations[selectedLanguage].tenthHead;
    document.querySelector('.tenth-btn').textContent = translations[selectedLanguage].tenthBtn;
    document.querySelector('.tenth-foot').textContent = translations[selectedLanguage].tenthFoot;
    document.querySelector('.footer-head').textContent = translations[selectedLanguage].footerHead;
    document.querySelector('.footer-head').textContent = translations[selectedLanguage].footerHead;
    document.querySelector('.footer-head').textContent = translations[selectedLanguage].footerHead;
    document.querySelector('.footer-head').textContent = translations[selectedLanguage].footerHead;
    document.querySelector('.footer-head').textContent = translations[selectedLanguage].footerHead;
    document.querySelector('.footer-head').textContent = translations[selectedLanguage].footerHead;
    document.querySelector('.footer-head').textContent = translations[selectedLanguage].footerHead;
    document.querySelector('.footer-head').textContent = translations[selectedLanguage].footerHead;
    document.querySelector('.footer-head').textContent = translations[selectedLanguage].footerHead;
    document.querySelector('.footer-head').textContent = translations[selectedLanguage].footerHead;
});
